// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorldRankGuesser.Api.Persistence;

#nullable disable

namespace WorldRankGuesser.Api.Persistence.Migrations;

[DbContext(typeof(GameDbContext))]
[Migration("20260919070050_InitialGameSchema")]
partial class _20260919070050_InitialGameSchema
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("game")
            .HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(id);

                b.Property<string>("FriendlyName")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Xml")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("DataProtectionKeys", "game");
            });

        modelBuilder.Entity("WorldRankGuesser.Api.Persistence.Board", b =>
            {
                var id = b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(id);

                b.Property<int>("Cap")
                    .HasColumnType("int");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<DateOnly?>("DailyDate")
                    .HasColumnType("date");

                b.Property<int>("OptimalScore")
                    .HasColumnType("int");

                b.Property<string>("RankMode")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("nvarchar(16)");

                b.Property<DateTimeOffset>("RankingsLoadedAt")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.HasIndex("DailyDate")
                    .IsUnique()
                    .HasFilter("[DailyDate] IS NOT NULL");

                b.ToTable("Boards", "game");
            });

        modelBuilder.Entity("WorldRankGuesser.Api.Persistence.Game", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<long>("BoardId")
                    .HasColumnType("bigint");

                b.Property<DateTimeOffset?>("CompletedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<DateOnly?>("DailyDate")
                    .HasColumnType("date");

                b.Property<string>("Mode")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("nvarchar(16)");

                b.Property<Guid>("PlayerId")
                    .HasColumnType("uniqueidentifier");

                b.Property<byte[]>("RowVersion")
                    .IsConcurrencyToken()
                    .IsRequired()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("rowversion");

                b.Property<DateTimeOffset>("StartedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<int?>("TotalScore")
                    .HasColumnType("int");

                b.Property<DateTimeOffset?>("TurnDeadline")
                    .HasColumnType("datetimeoffset");

                b.Property<int>("TurnIndex")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("BoardId");

                var index = b.HasIndex("DailyDate", "TotalScore");

                SqlServerIndexBuilderExtensions.IncludeProperties(index, new[] { "StartedAt", "CompletedAt" });

                b.HasIndex("PlayerId", "DailyDate")
                    .IsUnique()
                    .HasFilter("[DailyDate] IS NOT NULL");

                b.ToTable("Games", "game");
            });

        modelBuilder.Entity("WorldRankGuesser.Api.Persistence.Pick", b =>
            {
                b.Property<Guid>("GameId")
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("TurnIndex")
                    .HasColumnType("int");

                b.Property<string>("CategoryId")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("nvarchar(32)");

                b.Property<string>("ISO3")
                    .IsRequired()
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasColumnType("varchar(3)")
                    .HasColumnName("ISO3");

                b.Property<DateTimeOffset>("PickedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<int>("Score")
                    .HasColumnType("int");

                b.Property<bool>("WasLate")
                    .HasColumnType("bit");

                b.HasKey("GameId", "TurnIndex");

                b.HasIndex("GameId", "CategoryId")
                    .IsUnique();

                b.ToTable("Picks", "game");
            });

        modelBuilder.Entity("WorldRankGuesser.Api.Persistence.Player", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("BestStreak")
                    .HasColumnType("int");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<int>("CurrentStreak")
                    .HasColumnType("int");

                b.Property<string>("ExternalProvider")
                    .HasMaxLength(32)
                    .HasColumnType("nvarchar(32)");

                b.Property<string>("ExternalSubject")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateOnly?>("LastDailyDate")
                    .HasColumnType("date");

                b.Property<DateTimeOffset>("LastSeenAt")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("Nickname")
                    .HasMaxLength(24)
                    .HasColumnType("nvarchar(24)");

                b.HasKey("Id");

                b.HasIndex("ExternalProvider", "ExternalSubject")
                    .IsUnique()
                    .HasFilter("[ExternalProvider] IS NOT NULL AND [ExternalSubject] IS NOT NULL");

                b.ToTable("Players", "game");
            });

        modelBuilder.Entity("WorldRankGuesser.Api.Rankings.CountryRankingRow", b =>
            {
                b.Property<string>("Competitor")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Event")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Gender")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ISO3")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsFederationDate")
                    .HasColumnType("bit");

                b.Property<decimal?>("Points")
                    .HasPrecision(12, 3)
                    .HasColumnType("decimal(12,3)");

                b.Property<short>("Position")
                    .HasColumnType("smallint");

                b.Property<int?>("RankedEntrants")
                    .HasColumnType("int");

                b.Property<DateOnly>("RankingDate")
                    .HasColumnType("date");

                b.Property<string>("Sport")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("TeamName")
                    .HasColumnType("nvarchar(max)");

                b.ToTable((string)null);

                b.ToView("CurrentCountryRankings", "dbo");
            });

        modelBuilder.Entity("WorldRankGuesser.Api.Persistence.Game", b =>
            {
                b.HasOne("WorldRankGuesser.Api.Persistence.Board", "Board")
                    .WithMany()
                    .HasForeignKey("BoardId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("WorldRankGuesser.Api.Persistence.Player", "Player")
                    .WithMany()
                    .HasForeignKey("PlayerId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Board");

                b.Navigation("Player");
            });

        modelBuilder.Entity("WorldRankGuesser.Api.Persistence.Pick", b =>
            {
                b.HasOne("WorldRankGuesser.Api.Persistence.Game", null)
                    .WithMany("Picks")
                    .HasForeignKey("GameId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("WorldRankGuesser.Api.Persistence.Game", b =>
            {
                b.Navigation("Picks");
            });
#pragma warning restore 612, 618
    }
}
