/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StartGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetGame"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{id}/picks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Pick"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CategoryDto: {
            id: string;
            name: string;
        };
        CellDto: {
            /** Format: int32 */
            score: number;
            /** Format: int32 */
            countryRank: null | number;
            /** Format: int32 */
            entryRank: null | number;
            unranked: boolean;
            sport: null | string;
            event: null | string;
            gender: null | string;
            competitor: null | string;
        };
        CountryDto: {
            iso3: string;
            iso2: string;
            name: string;
        };
        GameStateDto: {
            /** Format: uuid */
            id: string;
            mode: string;
            /** Format: date */
            dailyDate: null | string;
            rankMode: string;
            /** Format: int32 */
            cap: number;
            categories: components["schemas"]["CategoryDto"][];
            picks: components["schemas"]["PickDto"][];
            currentCountry: null | components["schemas"]["CountryDto"];
            /** Format: date-time */
            deadline: null | string;
            /** Format: date-time */
            serverNow: string;
            isComplete: boolean;
            /** Format: int32 */
            totalScore: null | number;
            /** Format: int32 */
            optimalScore: null | number;
            grid: null | components["schemas"]["GridDto"];
        };
        GridDto: {
            countries: components["schemas"]["CountryDto"][];
            cells: components["schemas"]["CellDto"][][];
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        PickDto: {
            /** Format: int32 */
            turnIndex: number;
            categoryId: string;
            country: components["schemas"]["CountryDto"];
            /** Format: int32 */
            score: number;
            wasLate: boolean;
            result: components["schemas"]["CellDto"];
        };
        PickRequest: {
            categoryId: null | string;
        };
        StartGameRequest: {
            mode: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    StartGame: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartGameRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameStateDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameStateDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Pick: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PickRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameStateDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameStateDto"];
                };
            };
        };
    };
}
